"""Summary report generation for speaker labeling pipeline.

Generates:
1. General MD summary with overall statistics
2. Per-show MD summaries with detailed episode data
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from podcast_conversations.naming import sanitize_name
from podcast_conversations.speaker_labeling.types import (
    PipelineSummary,
    PodcastResult,
    SpeakerRole,
)

logger = logging.getLogger(__name__)


class SummaryGenerator:
    """Generates markdown summary reports."""

    def __init__(self, output_dir: Path):
        """
        Initialize generator.

        Args:
            output_dir: Directory to write summary files.
        """
        self.output_dir = output_dir
        self.summaries_dir = output_dir / "summaries"
        self.summaries_dir.mkdir(parents=True, exist_ok=True)

    def generate_all(self, summary: PipelineSummary) -> tuple[Path, list[Path]]:
        """
        Generate all summary reports.

        Args:
            summary: Pipeline summary data.

        Returns:
            Tuple of (general_summary_path, list_of_per_show_paths).
        """
        general_path = self.generate_general_summary(summary)
        per_show_paths = self.generate_per_show_summaries(summary)
        return general_path, per_show_paths

    def generate_general_summary(self, summary: PipelineSummary) -> Path:
        """Generate general statistics summary."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        lines = [
            "# Speaker Labeling Pipeline - Summary Report",
            "",
            f"**Generated:** {timestamp}",
            "",
            "## Overview",
            "",
            f"- **Total Podcasts:** {summary.total_podcasts}",
            f"- **Total Episodes Processed:** {summary.total_episodes_processed}",
            f"- **Total Episodes Failed:** {summary.total_episodes_failed}",
            f"- **Success Rate:** {self._success_rate(summary):.1f}%",
            "",
            "## Speaker Labeling Statistics",
            "",
            f"- **Total Speakers Labeled:** {summary.total_speakers_labeled}",
            f"- **Total Speakers Found:** {summary.total_speakers_found}",
            f"- **Labeling Rate:** {self._labeling_rate(summary):.1f}%",
            f"- **Average Confidence:** {summary.average_confidence:.2f}",
            "",
            "## Assignment Method Distribution",
            "",
            "| Method | Count | Percentage |",
            "|--------|-------|------------|",
        ]

        total_assignments = sum(summary.method_distribution.values()) or 1
        for method, count in sorted(
            summary.method_distribution.items(),
            key=lambda x: x[1],
            reverse=True,
        ):
            pct = (count / total_assignments) * 100
            lines.append(f"| {method} | {count} | {pct:.1f}% |")

        lines.extend([
            "",
            "## Role Distribution",
            "",
            "| Role | Count | Percentage |",
            "|------|-------|------------|",
        ])

        total_roles = sum(summary.role_distribution.values()) or 1
        for role, count in sorted(
            summary.role_distribution.items(),
            key=lambda x: x[1],
            reverse=True,
        ):
            pct = (count / total_roles) * 100
            lines.append(f"| {role} | {count} | {pct:.1f}% |")

        lines.extend([
            "",
            "## Per-Podcast Summary",
            "",
            "| Podcast | Episodes | Failed | Speakers Labeled | Avg Confidence |",
            "|---------|----------|--------|------------------|----------------|",
        ])

        for podcast_result in sorted(
            summary.podcast_results,
            key=lambda x: x.episodes_processed,
            reverse=True,
        ):
            labeled = sum(e.speakers_labeled for e in podcast_result.episode_results)
            confidences = [
                m.confidence
                for e in podcast_result.episode_results
                for m in e.mappings
            ]
            avg_conf = sum(confidences) / len(confidences) if confidences else 0

            lines.append(
                f"| {podcast_result.podcast_name} | "
                f"{podcast_result.episodes_processed} | "
                f"{podcast_result.episodes_failed} | "
                f"{labeled} | "
                f"{avg_conf:.2f} |"
            )

        lines.extend([
            "",
            "## Confidence Distribution",
            "",
            self._generate_confidence_histogram(summary),
            "",
            "---",
            "*Report generated by speaker labeling pipeline*",
        ])

        # write file.
        output_path = self.summaries_dir / "general_summary.md"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        logger.info(f"Generated general summary: {output_path}")
        return output_path

    def generate_per_show_summaries(self, summary: PipelineSummary) -> list[Path]:
        """Generate per-show detailed summaries."""
        paths = []

        for podcast_result in summary.podcast_results:
            path = self._generate_show_summary(podcast_result)
            paths.append(path)

        return paths

    def _generate_show_summary(self, podcast_result: PodcastResult) -> Path:
        """Generate summary for a single podcast."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        lines = [
            f"# {podcast_result.podcast_name} - Speaker Labeling Report",
            "",
            f"**Generated:** {timestamp}",
            "",
            "## Overview",
            "",
            f"- **Episodes Processed:** {podcast_result.episodes_processed}",
            f"- **Episodes Failed:** {podcast_result.episodes_failed}",
            "",
        ]

        # calculate statistics.
        all_mappings = [
            m for e in podcast_result.episode_results for m in e.mappings
        ]

        if all_mappings:
            avg_confidence = sum(m.confidence for m in all_mappings) / len(all_mappings)
            lines.extend([
                "## Labeling Statistics",
                "",
                f"- **Total Speakers Labeled:** {len(all_mappings)}",
                f"- **Average Confidence:** {avg_confidence:.2f}",
                "",
            ])

            # unique names found.
            names = set(m.name for m in all_mappings)
            hosts = [m.name for m in all_mappings if m.role == SpeakerRole.HOST]
            guests = [m.name for m in all_mappings if m.role == SpeakerRole.GUEST]

            lines.extend([
                "## Identified Speakers",
                "",
                "### Hosts",
                "",
            ])

            unique_hosts = set(hosts)
            for host in sorted(unique_hosts):
                count = hosts.count(host)
                lines.append(f"- **{host}** (appears in {count} episodes)")

            lines.extend([
                "",
                "### Guests",
                "",
            ])

            unique_guests = set(guests)
            for guest in sorted(unique_guests):
                lines.append(f"- {guest}")

        lines.extend([
            "",
            "## Episode Details",
            "",
            "| Episode | Speakers Labeled | Confidence | Mappings |",
            "|---------|------------------|------------|----------|",
        ])

        for ep_result in podcast_result.episode_results:
            ep_name = Path(ep_result.episode_file).stem[:50]
            confidence = (
                sum(m.confidence for m in ep_result.mappings) / len(ep_result.mappings)
                if ep_result.mappings else 0
            )
            mappings_str = ", ".join(
                f"{m.name}→{m.speaker_id}" for m in ep_result.mappings[:3]
            )
            if len(ep_result.mappings) > 3:
                mappings_str += "..."

            status = "✅" if ep_result.success else "❌"
            lines.append(
                f"| {status} {ep_name} | "
                f"{ep_result.speakers_labeled}/{ep_result.speakers_total} | "
                f"{confidence:.2f} | "
                f"{mappings_str} |"
            )

        # assignment method breakdown.
        method_counts: dict[str, int] = {}
        for m in all_mappings:
            method = m.assignment_method.value
            method_counts[method] = method_counts.get(method, 0) + 1

        if method_counts:
            lines.extend([
                "",
                "## Assignment Methods",
                "",
                "| Method | Count |",
                "|--------|-------|",
            ])

            for method, count in sorted(method_counts.items(), key=lambda x: x[1], reverse=True):
                lines.append(f"| {method} | {count} |")

        lines.extend([
            "",
            "---",
            "*Report generated by speaker labeling pipeline*",
        ])

        # write file.
        safe_name = sanitize_name(podcast_result.podcast_name)
        output_path = self.summaries_dir / f"{safe_name}_summary.md"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        logger.info(f"Generated show summary: {output_path}")
        return output_path

    def _success_rate(self, summary: PipelineSummary) -> float:
        """Calculate success rate percentage."""
        total = summary.total_episodes_processed + summary.total_episodes_failed
        if total == 0:
            return 0.0
        return (summary.total_episodes_processed / total) * 100

    def _labeling_rate(self, summary: PipelineSummary) -> float:
        """Calculate speaker labeling rate percentage."""
        if summary.total_speakers_found == 0:
            return 0.0
        return (summary.total_speakers_labeled / summary.total_speakers_found) * 100

    def _generate_confidence_histogram(self, summary: PipelineSummary) -> str:
        """Generate ASCII histogram of confidence distribution."""
        # collect all confidences.
        confidences = [
            m.confidence
            for pr in summary.podcast_results
            for er in pr.episode_results
            for m in er.mappings
        ]

        if not confidences:
            return "*No confidence data available*"

        # create buckets.
        buckets = [0] * 10  # 0.0-0.1, 0.1-0.2, ..., 0.9-1.0
        for conf in confidences:
            bucket = min(9, int(conf * 10))
            buckets[bucket] += 1

        # find max for scaling.
        max_count = max(buckets) or 1

        lines = ["```"]
        for i, count in enumerate(buckets):
            low = i / 10
            high = (i + 1) / 10
            bar_width = int((count / max_count) * 40)
            bar = "█" * bar_width
            lines.append(f"{low:.1f}-{high:.1f}: {bar} ({count})")
        lines.append("```")

        return "\n".join(lines)


def create_summary_generator(output_dir: Path) -> SummaryGenerator:
    """Factory function to create summary generator.

    Args:
        output_dir: Output directory.

    Returns:
        Configured SummaryGenerator.
    """
    return SummaryGenerator(output_dir)
